language: node_js
node_js:
  - "10"
install:
  - npm install
  - npm run generate
script:
  - echo "No tests"
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master