language: node_js
node_js:
  - "10"
install:
  - npm install
script:
  - echo "Starting tests"
  # Test
  - npm run test
  # Run cypress tests
  - npm run cy:run
  # Stop development local server
  - kill $(jobs -p) || true
  - npm run generate
cache:
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache
deploy:
  provider: pages
  skip-cleanup: tru
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master